import { ShieldAlert, Eye, Brain, Globe } from 'lucide-react';

const challenges = [
  {
    icon: ShieldAlert,
    title: 'The Threat of Deepfakes',
    desc: 'Synthetic media generated by generative adversarial networks (GANs) and diffusion models poses significant risks to information integrity, political discourse, and personal safety.',
  },
  {
    icon: Eye,
    title: 'Detection Challenges',
    desc: 'State-of-the-art generation techniques produce highly realistic fakes that are increasingly difficult to distinguish from authentic media with the naked eye.',
  },
  {
    icon: Brain,
    title: 'Our Approach',
    desc: 'We leverage transfer learning with EfficientNet-B0 pretrained on ImageNet, fine-tuned on a curated real vs. fake dataset to learn subtle manipulation artifacts.',
  },
  {
    icon: Globe,
    title: 'Real-World Impact',
    desc: 'This tool demonstrates how deep learning can serve as a first-line defense in media forensics, journalism, and content moderation pipelines.',
  },
];

export default function About() {
  return (
    <section className="min-h-screen bg-neutral pt-28 pb-20 px-6">
      <div className="max-w-5xl mx-auto">
        <div className="text-center mb-14">
          <h2 className="text-3xl md:text-4xl font-bold text-charcoal mb-4 tracking-tight">
            About This Project
          </h2>
          <p className="text-slate-500 text-lg max-w-2xl mx-auto leading-relaxed">
            An academic machine learning project exploring automated deepfake detection using convolutional neural networks and modern computer vision techniques.
          </p>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 gap-6 mb-12">
          {challenges.map(({ icon: Icon, title, desc }) => (
            <div
              key={title}
              className="bg-white rounded-2xl border border-slate-200 shadow-sm p-7 hover:shadow-md hover:-translate-y-0.5 transition-all duration-200"
            >
              <div className="w-12 h-12 rounded-xl bg-navy/5 flex items-center justify-center mb-5">
                <Icon className="w-6 h-6 text-navy" />
              </div>
              <h3 className="font-bold text-charcoal text-lg mb-2">{title}</h3>
              <p className="text-slate-500 leading-relaxed">{desc}</p>
            </div>
          ))}
        </div>

        <div className="bg-gradient-to-br from-navy to-slate rounded-2xl p-8 md:p-10 text-white">
          <div className="max-w-2xl">
            <h3 className="text-2xl font-bold mb-4">Research Motivation</h3>
            <p className="text-slate-300 leading-relaxed mb-4">
              As generative AI tools become more accessible, the gap between real and synthetic media continues to narrow. This project addresses the urgent need for automated forensic tools that can assist humans in identifying manipulated content.
            </p>
            <p className="text-slate-300 leading-relaxed">
              The system is designed as a demonstration prototype, suitable for integration into larger content verification pipelines. All predictions should be treated as supplementary evidence and interpreted alongside human judgment.
            </p>
            <div className="mt-6 flex items-center gap-2">
              <span className="w-2 h-2 rounded-full bg-cyan-400 animate-pulse" />
              <span className="text-cyan-400 text-sm font-medium">Developed as an ML Project Demonstration · 2024</span>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
}
